### ISSUE TITLE
Add integration test for Infrastructure reconciliation and deletion

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener-extension-provider-gcp#106]
**How to categorize this issue?**

/area testing
/kind enhancement
/priority normal
/platform gcp

**What would you like to be added**:
With https://github.com/gardener/gardener-extension-provider-aws/pull/54 provider-aws features integration test for Infrastructure reconciliation and deletion.

**Why is this needed**:
I would be good if we have similar test for provider-gcp as it will increase the robustness.

**Comment by gardener-botmanager** [comment]
@ialidzhikov Label area/testing does not exist.
