### ISSUE TITLE
Remove IPIP Tunnels from GCP

### ISSUE THREAD

**Issue by zanetworker** [gardener/gardener-extension-provider-gcp#115]
**How to categorize this issue?**
/area networking
/kind enhancement

**What would you like to be added**:

Today, the `cloud-controller-manager` is used to configure routes on GCP (`configure-cloud-routes=true`), however these routes are not used since we are utilizing CNI tunnels (e.g., IPIP or VxLAN) to enabled pod-connectivity cross nodes and zones. 

To completely remove tunnels for GCP, we would need to disable IPIP tunnels on Calico (e.g., via a webhook similar to Azure Setup `backend=none`). Furthermore, we need to deploy [`ip-masq-agent`](https://github.com/kubernetes-sigs/ip-masq-agent) to prevent Pod generated traffic from being blocked by the GCP infrastructure . 

**Why is this needed**:
- Improve pod routing performance. 
- Avoid possible overlaps between tunnel and cluster CIDRs.
- Eliminate MTU inconsistencies.

**Comment by rfranzke** [comment]
Any changes to CCM required?

**Comment by zanetworker** [comment]
Nope, since `configure-cloud-routes` is statically configured to `true` today by default (not sure why but helps now)

**Comment by danielfoehrKn** [comment]
Does this mean that Calico is not used for networking anymore on GCP but only for network policy enforcement? Maybe you could share some insights. Thanks!

**Comment by zanetworker** [comment]
@danielfoehrKn yes, it will be like Azure.

**Comment by vpnachev** [comment]
Reopen because #117 was reverted with #136.
