### ISSUE TITLE
Add support for Node Accelerators (GPU/TPU)  

### ISSUE THREAD

**Issue by afritzler** [gardener/gardener-extension-provider-gcp#132]
**How to categorize this issue?**
/component mcm
/kind enhancement
/priority normal
/platform gcp

**What would you like to be added**:
In order to allow the usage of GPU/TPU nodes on GCP we need to enable the `guest_accelerators` when machines are being created.

In Terraform speak this would look something like this:

```shell
    guest_accelerator = [
      {
        type = "${var.gpu_type}"
        count = "${var.gpu_per_node}"
      }]
```

Of course this needs to be translated to the go sdk usage.

**Why is this needed**:
The use case here is to allow ML workload on GCP cluster.

**Comment by vlerenc** [comment]
We got some push here, so people have interest. Do we know how much effort that would be after out-of-tree?

**Comment by hardikdr** [comment]
Not much, from the looks of it,  for MCM.
As it can be combined with the creation-call, we simply have to introduce the `guest_accelerators` related fields in the `Spec` of MachineClass, and map it to the go-sdk. Also, GCP-OOT provider is ready, and about to be deployed with the next extension-release.

Then we need to adapt gcp-worker-extension and shoot-spec to expose to it to the user. Unless there is a known blocker, this should simply follow the existing code-path.

**Comment by vlerenc** [comment]
@ashwani2k @himanshu-kun FYI
