### ISSUE TITLE
Unable to create internal LoadBalancer

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener-extension-provider-gcp#150]
**How to categorize this issue?**

/area networking
/kind bug
/priority normal
/platform gcp

**What happened**:
Unable to create internal LoadBalancer. Ref https://cloud.google.com/kubernetes-engine/docs/how-to/internal-load-balancing

**What you expected to happen**:
To be able to create internal LoadBalancer.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create Service with annotation ` networking.gke.io/load-balancer-type: "Internal"`

```bash 
$ cat <<EOF | kubectl apply -f -
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app
spec:
  selector:
    matchLabels:
      app: hello
  replicas: 3
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello
        image: "gcr.io/google-samples/hello-app:2.0"
---
apiVersion: v1
kind: Service
metadata:
  name: ilb-service
  annotations:
    networking.gke.io/load-balancer-type: "Internal"
  labels:
    app: hello
spec:
  type: LoadBalancer
  selector:
    app: hello
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
EOF
```

2. Ensure that the Service hangs in pending state

```
$ k describe svc ilb-service

Events:
  Type     Reason                  Age                 From                Message
  ----     ------                  ----                ----                -------
  Normal   EnsuringLoadBalancer    0s (x7 over 5m17s)  service-controller  Ensuring load balancer
  Warning  SyncLoadBalancerFailed  0s (x7 over 5m16s)  service-controller  Error syncing load balancer: failed to ensure load balancer: services "ilb-service" is forbidden: User "system:serviceaccount:kube-system:cloud-provider" cannot patch resource "services/status" in API group "" in the namespace "default"
```

**Anything else we need to know?**:

**Environment**:

- Gardener version (if relevant):
- Extension version: v1.9.0
- Kubernetes version (use `kubectl version`): v1.18.5
- Cloud provider or hardware configuration:
- Others:

**Comment by ialidzhikov** [comment]
@dguendisch , isn't there already a conformance test about ILBs? We apparently don't test this as it requires configuring internal subnet as part of the Shoot spec...

**Comment by dguendisch** [comment]
@ialidzhikov there is one in the e2e suite (not conformance): https://github.com/kubernetes/kubernetes/blob/09d6512ed31943c1120b4c4970e878e494706f0e/test/e2e/network/service.go#L2256

However we decided (for whatever reason) to skip this particular one when executing the extended e2e suite (again, not the conformance suite): https://github.com/gardener/test-infra/blob/master/integration-tests/e2e/kubetest/description/1.18/skip.json#L140
