### ISSUE TITLE
Adopt CSI for GCP extension beginning with Kubernetes 1.18

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener-extension-provider-gcp#2]
As of Kubernetes 1.17 the in-tree GCE PD volume driver is deprecated in favour of CSI. We should adopt CSI for 1.17+ clusters.

See also: https://github.com/kubernetes/kubernetes/pull/85231 and https://kubernetes.io/blog/2019/12/09/kubernetes-1-17-feature-csi-migration-beta/

**Comment by ialidzhikov** [comment]
Fixed with #61.

/close
