### ISSUE TITLE
csi-node-driver-registrar preStopHook failing

### ISSUE THREAD

**Issue by timebertt** [gardener/gardener-extension-provider-gcp#244]
**How to categorize this issue?**

/area storage
/kind bug
/priority normal
/platform gcp

**What happened**:

When rolling the `csi-driver-node`, I noticed one pod refusing to terminate and the `preStopHook` failing with the following error:

```text
Events:
  Type     Reason             Age                   From     Message
  ----     ------             ----                  ----     -------
  Normal   Killing            3m8s                  kubelet  Stopping container csi-liveness-probe
  Normal   Killing            3m8s                  kubelet  Stopping container csi-node-driver-registrar
  Warning  FailedPreStopHook  3m8s                  kubelet  Exec lifecycle hook ([/bin/sh -c rm -rf /registration/pd.csi.storage.gke.io-reg.sock /csi/csi.sock]) for Container "csi-node-driver-registrar" in Pod "csi-driver-node-qfhnf_kube-system(fb77f204-f9c7-4d84-8970-77cdbfe8ad7b)" failed - error: command '/bin/sh -c rm -rf /registration/pd.csi.storage.gke.io-reg.sock /csi/csi.sock' exited with 126: , message: "OCI runtime exec failed: exec failed: container_linux.go:370: starting container process caused: exec: \"/bin/sh\": stat /bin/sh: no such file or directory: unknown\r\n"
  Warning  Unhealthy          2m21s (x5 over 3m1s)  kubelet  Liveness probe failed: Get http://10.242.0.92:9808/healthz: dial tcp 10.242.0.92:9808: connect: connection refused
  Warning  FailedKillPod      68s                   kubelet  error killing pod: failed to "KillContainer" for "csi-driver" with KillContainerError: "rpc error: code = Unknown desc = operation timeout: context deadline exceeded"
  Normal   Killing            67s (x2 over 3m8s)    kubelet  Stopping container csi-driver
```

The pod was hanging for another `~5m`.

**What you expected to happen**:

The `csi-driver-node` pod to properly terminate so that rolls can continue.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- Gardener version (if relevant):
- Extension version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by vlerenc** [comment]
@timebertt Since [this](https://github.com/gardener/gardener-extension-provider-gcp/issues/244#issuecomment-803856823) happens again and again, maybe the team likes to update the templates to the numbered priorities that were introduced for better roadmap planning in the future (throughout all repos that you have and where you have that in the template)?

**Comment by ialidzhikov** [comment]
> @timebertt Since [this](https://github.com/gardener/gardener-extension-provider-gcp/issues/244#issuecomment-803856823) happens again and again, maybe the team likes to update the templates to the numbered priorities that were introduced for better roadmap planning in the future (throughout all repos that you have and where you have that in the template)?

Already done with https://github.com/gardener/gardener/pull/3729. Will be fixed in the extension repos after revendoring.
