### ISSUE TITLE
ControllerManager Feature Gate CustomResourceValidation no longer exists

### ISSUE THREAD

**Issue by voelzmo** [gardener/gardener-extension-provider-gcp#263]
**How to categorize this issue?**
/area documentation
/kind bug
/priority 3
/platform gcp

**What happened**:
As specified in the [shoot example file](https://github.com/gardener/gardener/blob/master/example/90-shoot.yaml#L26) I used the GCP extension provider's [control plane example file](https://github.com/gardener/gardener-extension-provider-gcp/blob/master/example/30-controlplane.yaml#L60-L62) to get an understanding of what the `providerConfig` should look like. Turns out that specifying the feature flag `CustomResourceValidation` makes the installation process fail in the gcp-cloud-controller-manager with 
```
error: invalid argument "CustomResourceValidation=true" for "--feature-gates" flag: unrecognized feature gate: CustomResourceValidation
```

**What you expected to happen**:
shoot is successfully reconciled

**How to reproduce it (as minimally and precisely as possible)**:
* create a new empty seed with gcp as extension provider for the Iaas (probably also works with other providers which have the same example configuration)
* create a shoot, taking input for https://github.com/gardener/gardener/blob/master/example/90-shoot.yaml#L26 from https://github.com/gardener/gardener-extension-provider-gcp/blob/master/example/30-controlplane.yaml#L60-L62
* watch installation of cloud-controller-manager in your new shoot fail with above error

**Anything else we need to know?**:
This might be due to the fact that `CustomResourceValidation` is GA since k8s 1.16? See https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/

**Environment**:

- Gardener version (if relevant):  1.21.0
- Extension version: 1.16.0
- Kubernetes version (use `kubectl version`): 1.21.0

**Comment by rfranzke** [comment]
Feature gates are not validated today, neither in g/g nor in any extension. There is https://github.com/gardener/gardener/issues/3987 where it is being discussed whether we should introduce it. If the decision is 'yes' then we might to have it as well for the provider extensions. 👍🏻

**Comment by rfranzke** [comment]
cc @vpnachev as you want to work on this week :)
