### ISSUE TITLE
Support for provisioning Gardener with Shared VPC in GCP

### ISSUE THREAD

**Issue by kapilraju** [gardener/gardener-extension-provider-gcp#291]
/area networking
/kind enhancement
/priority 1
/platform gcp

**What would you like to be added:**
Gardener doesn't support creating Kubernetes cluster using GCP shared VPC. It fails to create the cluster because gardener cannot detect exported subnets(shared-vpc) in GCP service project and it detects only VPCs created locally in the service project
 
**Why is this needed:**
Shared VPC lets organization administrators to delegate administrative responsibilities to Service Project Admins(such as creating and managing instances) while maintaining centralized control over network resources like subnets, routes, and firewalls.

Using Shared VPC  is also a Google recommended architecture

**Comment by prashanth26** [comment]
Duplicate of https://github.com/gardener/gardener-extension-provider-gcp/issues/262?

**Comment by kapilraju** [comment]
@prashanth26 Yes, this duplicate of #262

**Comment by kapilraju** [comment]
@prashanth26 Can you please reopen this and close #262 , i don't have edit privilege for #262 to make changes to that post

**Comment by kapilraju** [comment]
@vlerenc @prashanth26 

Do you need any additional information to consider this feature request?

**Comment by vpnachev** [comment]
> @prashanth26 Can you please reopen this and close #262 , i don't have edit privilege for #262 to make changes to that post

But you can comment which is fine.

**Comment by prashanth26** [comment]
> @prashanth26 Can you please reopen this and close #262 , i don't have edit privilege for #262 to make changes to that post

Is there any specific reason for this? If it's to add more description, feel free to comment on the [other issue](https://github.com/gardener/gardener-extension-provider-gcp/issues/262). 


> @vlerenc @prashanth26
> 
> Do you need any additional information to consider this feature request?

No. We will try to pick this up.
