### ISSUE TITLE
Need the ability to create nodes on an existing VPC/subnet

### ISSUE THREAD

**Issue by rakewill** [gardener/gardener-extension-provider-gcp#32]
**What would you like to be added**:
Although it is possible to configure Gardener clusters to create nodes in a particular VPC, it still attempts to create a new subnet in the VPC. We would like to be able to specify both the name of an existing VPC and the name of an existing subnet within the VPC when creating a new cluster.
**Why is this needed**:
We have an existing VPC and subnet configured with PCI connectivity to the SAP corporate network. We need to configure all of our Kubernetes clusters to have nodes on the existing subnet.

**Comment by DockToFuture** [comment]
For my understanding,  do you want to provide one subnet which should be used by multiple shoot clusters with each of them using a different cidr chunk for the nodes of the subnet cidr. Or do you want to bring for each cluster an own subnet?

**Comment by rakewill** [comment]
We have found an alternate solution so we no longer require this work.
