### ISSUE TITLE
[Flaky Test] Bastion integration test is flaky

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener-extension-provider-gcp#359]
**How to categorize this issue?**

/area testing
/kind flake
/priority 3
/platform gcp

**Which test(s)/suite(s) are flaking**:
`Bastion tests [It] should successfully create and delete`

**CI link**:
- https://tm.gardener.cloud/testrun/default/e2e-xnhtd (ref https://github.com/gardener/gardener-extension-provider-gcp/pull/358#issuecomment-986261128)
- https://tm.gardener.cloud/testrun/default/e2e-2bjzs (ref https://github.com/gardener/gardener-extension-provider-gcp/pull/345#issuecomment-974218454)

**Reason for failure**:
While looking into the failure reason there were 165 rateLimitExceeded errors like the below one:

```
2021-12-05T16:40:26.570Z	ERROR	bastion_controller	error	{"namespace": "gcp-bastion-it--12345", "name": "gcp-bastion-it--12345-bastion", "error": "Error deleting bastion: failed to remove bastion instance: failed to terminate bastion instance: googleapi: Error 403: Too many pending operations on a resource., rateLimitExceeded"}
```

However this seems to be a different issue from the error that actually caused the test failure:

```
STEP: check connection to port 22 open should not error

• Failure [62.976 seconds]
Bastion tests
/src/test/integration/bastion/bastion_test.go:77
  should successfully create and delete [It]
  /src/test/integration/bastion/bastion_test.go:196

  Unexpected error:
      <*net.OpError | 0xc00227caf0>: {
          Op: "dial",
          Net: "tcp4",
          Source: nil,
          Addr: <*net.TCPAddr | 0xc000d37e00>{
              IP: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 255, 255, 34, 79, 18, 202],
              Port: 22,
              Zone: "",
          },
          Err: <*os.SyscallError | 0xc000b77160>{
              Syscall: "connect",
              Err: <syscall.Errno>0x6f,
          },
      }
      dial tcp4 34.79.18.202:22: connect: connection refused
  occurred

  /src/test/integration/bastion/bastion_test.go:252
```

**Anything else we need to know**:

**Comment by tedteng** [comment]
It may `rateLimitExceeded` cause operation delay to apply firewall rule to open port 22 before executing next 22 port check

**Comment by tedteng** [comment]
https://github.com/gardener/gardener-extension-provider-gcp/pull/364#issuecomment-995759256
new error from test result 
```
2021-12-17 08:38:04 | Ran 1 of 1 Specs in 182.392 seconds
-- | --
  |   | 2021-12-17 08:38:04 |  
  |   | 2021-12-17 08:38:04 | ------------------------------
  |   | 2021-12-17 08:38:04 | /src/test/integration/bastion/bastion_test.go:569
  |   | 2021-12-17 08:38:04 |  
  |   | 2021-12-17 08:38:04 | <nil>: nil
  |   | 2021-12-17 08:38:04 | Expected an error to have occurred.  Got:
  |   | 2021-12-17 08:38:04 |  
  |   | 2021-12-17 08:38:04 | /src/test/integration/bastion/bastion_test.go:183
```

**Comment by ialidzhikov** [comment]
> will take a look after completing my current task.

Why you don't look into this issue right now?

**Comment by tedteng** [comment]
> > will take a look after completing my current task.
> 
> Why you don't look into this issue right now?
last week was busy on the OpenStack extension which I was submitted this Monday.  also one sick leave yesterday.  now I'm able to work on this task

**Comment by tedteng** [comment]
Hi @ialidzhikov feel free to review when you are available thanks.
