### ISSUE TITLE
Add validation to prevent worker.min to be set to 0.

### ISSUE THREAD

**Issue by hardikdr** [gardener/gardener-extension-provider-gcp#46]
**What would you like to be added**: We need to add the validation to prevent the worker.Min from being set to 0 when worker.Max is non-zero.  This is to avoid cluster-autoscaler from scaling down the worker-pool to zero, and not being able to scale-up later.

**Why is this needed**:
Please refer for more info.: https://github.com/gardener/gardener/pull/2045

**Comment by timuthy** [comment]
Solved by https://github.com/gardener/gardener-extension-provider-gcp/pull/38
