### ISSUE TITLE
Enable "Block Project-wide SSH Keys" option in worker nodes of shoot cluster in Google Cloud 

### ISSUE THREAD

**Issue by hariprasath91** [gardener/gardener-extension-provider-gcp#510]
**How to categorize this issue?**
/area --> /auto-scaling
/kind bug 

**What happened**:
When we create a Cluster in gardener with Google Cloud provider , we see the SSH Keys on the Google side for the appropriate worker nodes getting enabled .
This is considered as a security constrain for SAP Complaint perspective

**What you expected to happen**:
We need to enable a option "Block Project-wide SSH Keys" for Google Cloud on the worker nodes which is getting deployed by Gardener . 
If any ssh key pair are maintained project metadata and enabling this option will break  login with this keys.
GCP doc: https://cloud.google.com/compute/docs/connect/restrict-ssh-keys

**How to reproduce it (as minimally and precisely as possible)**:
We can create a cluster and we see the option "Block Project-wide SSH Keys" getting disabled.
Please find the Screenshot
![image](https://user-images.githubusercontent.com/116298192/197010794-12173157-cb9f-49cd-aacc-b50e2b7e3ca3.png)

**Environment**: Google Cloud 

- Gardener version:  1.61.0
- Kubernetes version (use `kubectl version`): 
`
root@W-PF26JKWM:~# kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.15", GitCommit:"1d79bc3bcccfba7466c44cc2055d6e7442e140ea", GitTreeState:"clean", BuildDate:"2022-09-21T12:12:26Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
root@W-PF26JKWM:~# `
- Cloud provider or hardware configuration: Google Cloud 

Regards,
Hariprasath

**Comment by ialidzhikov** [comment]
Fixed with https://github.com/gardener/gardener-extension-provider-gcp/pull/506

/close
