### ISSUE TITLE
Only configure pod routes in VPC if pod overlay network is disabled

### ISSUE THREAD

**Issue by ScheererJ** [gardener/gardener-extension-provider-gcp#558]
**How to categorize this issue?**

/area networking
/area control-plane
/kind enhancement
/platform gcp

**What would you like to be added**:
If overlay network is enabled the cloud routes should not be enabled.

**Why is this needed**:
https://cloud.google.com/vpc/docs/quota#vpc-peering describes that GCP has a default limit of 300 static routes. If a cluster grows beyond 300 nodes or the VPC is shared among multiple clusters with together over 300 nodes the limit might be hit even though the cloud routes are not required if overlay network is enabled.

**Comment by kon-angelo** [comment]
Resolved with: https://github.com/gardener/gardener-extension-provider-gcp/pull/561
