### ISSUE TITLE
Add LocationType as multi-region for creating bucket

### ISSUE THREAD

**Issue by abdasgupta** [gardener/gardener-extension-provider-gcp#680]
**How to categorize this issue?**

/area control-plane
/area high-availability
/kind enhancement
/platform gcp

**What would you like to be added**:

Currently buckets in GCP are created with no LocationType [mentioned](https://github.com/gardener/gardener-extension-provider-gcp/blob/c90f1642bec8121a6de9f551eb197228fa649818/pkg/gcp/client/storage.go#L70C101-L70C101). So, it takes the default LocationType which is `region` and not replicated. Refer to https://pkg.go.dev/cloud.google.com/go/storage#section-readme

This backup-bucket is then used by etcd to store backups (full and delta snapshots) which are essential for restoration of the etcd cluster.

**Why is this needed**:
Change to LocationType as `multi-region` would help in adding resiliency in case zonal failures.

> **_NOTE:_**
>
> Migration can be done using https://cloud.google.com/storage-transfer/docs/cloud-storage-to-cloud-storage
There will be an impact on the cost. See [here](https://cloud.google.com/storage/pricing?_ga=2.13845879.-1529906661.1704880957) for more details.

**Comment by shreyas-s-rao** [comment]
This is not required at the moment, since we currently use `LocationType: region`, which provides zonal replication by default. We can explore using multi-region buckets when Gardener needs to support multi-regional shoot control planes, if and when that need arises.

/close
