### ISSUE TITLE
Integrate vSMP MemeoryOne in GCP

### ISSUE THREAD

**Issue by YakovKugel** [gardener/gardener-extension-provider-gcp#695]
**How to categorize this issue?**

/area usability
/area os
/kind enhancement

**What would you like to be added**:
Gardener already supports multi-volume connection for machines used by MemeoryONE in AWS , to boot OS and MemeoryOne software on the same worker-node on separate dataVolumes. 
The same functionality needed in GCP for MemoryONE worker-nodes. 

I would post here a link to an epic for the similar functionality requested in AWS in the past. 
https://github.com/gardener/gardener/issues/2354

**Why is this needed**:

**Comment by elankath** [comment]
@YakovKugel  We provided a small enhancement proposal.

PS: can you please give link to the latest vSMP Memory One user guide ? All the old links are broken.

**Comment by YakovKugel** [comment]
Hello Tarun,

Attaching here a MemoryOne user guide.
Fill free to reach out to me if you have questions.

Best Regards,
Yakov Kugel
