### ISSUE TITLE
GCP support additional volume

### ISSUE THREAD

**Issue by qiffang** [gardener/gardener-extension-provider-gcp#70]
**What would you like to be added**:
In the worker object, there are 2 fields `Volume` and `DataVolumes`
![image](https://user-images.githubusercontent.com/7285248/79858258-b5e8fb80-8401-11ea-869f-ba270fa106db.png)

But in gcp disk, there is only `Volume` field used.
![image](https://user-images.githubusercontent.com/7285248/79858311-cf8a4300-8401-11ea-84be-7052fd44b271.png)

I need 2 volume

- Root volume

- Local SSD volume

Can i submit a Pull Request to support it?

**Comment by rfranzke** [comment]
Can you get in touch with @guydaichs? AFAIK is he working on this feature?

**Comment by guydaichs** [comment]
Hi, MCM already supports multiple volumes for GCP, and we recently added support for this in gardener core and extension APIs. The only thing missing is the translation layer in provider-gcp. It should be pretty simple (sketch here: https://github.com/guydaichs/gardener-extension-provider-gcp/commit/0070165b0ad3f549d3e55e295e3410cb336e667d, tested it a while ago and it worked fine). Help is always appreciated, please go ahead and create a PR.

**Comment by qiffang** [comment]
Hi @rfranzke @guydaichs 
The pr is https://github.com/gardener/gardener-extension-provider-gcp/pull/71

**Comment by dkistner** [comment]
I guess as the referenced PR is merged we can close this issue.
