### ISSUE TITLE
cloudNAT settings can't be changed

### ISSUE THREAD

**Issue by champoeva** [gardener/gardener-extension-provider-gcp#74]
**What happened**:
I tried changing the cloudNAT setting in one of my teams cluster's shoot, as it is described here https://github.com/gardener/gardener-extension-provider-gcp/blob/master/docs/usage-as-end-user.md. When I tried to 'Save' my changes the following error appeared "admission webhook "validation.gcp.provider.extensions.gardener.cloud" denied the request: spec.provider.infrastructureConfig.networks: Invalid value: gcp.NetworkConfig{VPC:(*gcp.VPC)(nil), CloudNAT:(*gcp.CloudNAT)(0xc000499b20), Internal:(*string)(nil), Worker:"10.250.0.0/19", Workers:"", FlowLogs:(*gcp.FlowLogs)(nil)}: field is immutable"

**What you expected to happen**:
I expect the modification of the cloudNAT settings to be allowed.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Gardener version (if relevant):
- Extension version: 1.5.1
- Kubernetes version (use `kubectl version`): 1.16.8
- Cloud provider or hardware configuration:
- Others:

**Comment by rfranzke** [comment]
cc @zanetworker

**Comment by zanetworker** [comment]
@champoeva which values were you trying to change?

**Comment by champoeva** [comment]
I was trying to put this:
cloudNAT:
  minPortsPerVM: 2048
  natIPNames:
    - name: xf-factory-cloud-router-external-ip

under 'networks'
