### ISSUE TITLE
Support add custom label on GCP compute engine vm 

### ISSUE THREAD

**Issue by sdojjy** [gardener/gardener-extension-provider-gcp#82]
**What would you like to be added**:
In pkg/controller/worker/machines.go,  the machineClassSpec  labels map only contains one key named "name",  can we all pool labels to the machineClassSpec?  
```
	machineClassSpec := map[string]interface{}{
				"region":             w.worker.Spec.Region,
				"zone":               zone,
				"canIpForward":       true,
				"deletionProtection": false,
				"description":        fmt.Sprintf("Machine of Shoot %s created by machine-controller-manager.", w.worker.Name),
				"disks":              disks,
				"labels": map[string]interface{}{
					"name": w.worker.Name,
				},
```
By the way, AWS extension needs this feature too.

**Why is this needed**:
We need some custom labels to distinguish  VM, then we can charge our tenant by query the cost from the big query.

If it's possible, I can submit a PR to do this

**Comment by rfranzke** [comment]
Does https://github.com/gardener/gardener/blob/master/example/90-shoot.yaml#L51-L52 help?

**Comment by sdojjy** [comment]
@rfranzke no, the labels on workers are added to the Kubernetes node. not the VM on the GCP console portal.

**Comment by rfranzke** [comment]
Hm, the VMs should be tagged with the cluster name, or? Isn't this enough?

**Comment by sdojjy** [comment]
it's not enough for us, we need more labels to distinguish VM nodes.

**Comment by rfranzke** [comment]
I see.

> The simplest way is just to reuse the worker labels, add them to VM and k8s note at the same time.

What are the length restrictions for labels on VMs?

**Comment by sdojjy** [comment]
I think it's based on the cloud provider.

**Comment by rfranzke** [comment]
Sure. How is it for GCP (as this issue is on the GCP repo)?

**Comment by sdojjy** [comment]
For AWS:
you can apply standard base-64 encoding to your tag. 
https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/allocation-tag-restrictions.html

**Comment by sdojjy** [comment]
any update?

**Comment by rfranzke** [comment]
> The simplest way is just to reuse the worker labels, add them to VM and k8s note at the same time.

I think this is fair, but I guess Kubernetes labels may have 64 characters, so for GCP we'd have to trim them to 63, right?

Another option would be to introduce special keys and only transport those labels to the VM itself, i.e.

```yaml
labels:
  foo: bar
  machine.worker.gardener.cloud/<some-key>: <some-label>
```

For example, only the `foo=bar` would not be added to the VM (only to the Kubernetes node object).

I'm okay with both options, WDYT? Also, if you have time to file a PR for this it's more than appreciated/welcome! :)

**Comment by sdojjy** [comment]
thanks, I will file a PR
